const router = require('express').Router();
const schemes = [
  {id:1,name:'PM-KISAN',fullName:'Pradhan Mantri Kisan Samman Nidhi',fullNameMarathi:'प्रधानमंत्री किसान सन्मान निधी',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Income support of ₹6,000/year in three installments of ₹2,000 directly to bank accounts of all landholding farmers.',descriptionMarathi:'सर्व जमीनधारक शेतकऱ्यांना दरवर्षी ₹6,000 उत्पन्न सहाय्य. ₹2,000 च्या 3 हप्त्यांमध्ये थेट बँक खात्यात.',benefits:['₹6,000 annual income support','Direct Bank Transfer (DBT)','Three equal installments of ₹2,000','No middlemen involved'],eligibility:['All landholding farmer families','Small & marginal farmers','Land ownership documents required'],documents:['Aadhaar Card','Bank Passbook','Land Records (7/12 Utara)','Mobile Number'],howToApply:'Visit nearest CSC center or register at pmkisan.gov.in',link:'https://pmkisan.gov.in',category:'income-support',color:'#16a34a'},
  {id:2,name:'KCC',fullName:'Kisan Credit Card Scheme',fullNameMarathi:'किसान क्रेडिट कार्ड योजना',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Provides farmers timely credit at subsidized interest rates of 4% per annum for crop cultivation and allied activities.',descriptionMarathi:'शेतकऱ्यांना पीक लागवडासाठी 4% व्याजदराने वेळेवर कर्ज.',benefits:['Credit up to ₹3 lakh at 4% interest','No collateral up to ₹1.6 lakh','Flexible repayment aligned to harvest','Personal accident insurance'],eligibility:['Individual farmers','Tenant farmers & sharecroppers','SHG members'],documents:['Aadhaar Card','Land Records','Bank Account','Passport Photo'],howToApply:'Apply at nearest bank branch or online',link:'https://agricoop.nic.in/en/kisan-credit-card',category:'credit',color:'#2563eb'},
  {id:3,name:'PMFBY',fullName:'Pradhan Mantri Fasal Bima Yojana',fullNameMarathi:'प्रधानमंत्री फसल बीमा योजना',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Crop insurance providing financial support for losses due to natural calamities, pests & diseases.',descriptionMarathi:'नैसर्गिक आपत्ती, कीड आणि रोगांमुळे पीक नुकसानीसाठी आर्थिक सहाय्य.',benefits:['Premium only 2% Kharif, 1.5% Rabi','Government pays remaining premium','Quick satellite/drone-based settlement','Coverage for prevented sowing too'],eligibility:['All farmers growing notified crops','Both loanee and non-loanee farmers'],documents:['Aadhaar Card','Bank Account','Land Records','Sowing Certificate'],howToApply:'Apply at bank, CSC, or pmfby.gov.in before cutoff',link:'https://pmfby.gov.in',category:'insurance',color:'#dc2626'},
  {id:4,name:'eNAM',fullName:'National Agriculture Market',fullNameMarathi:'राष्ट्रीय कृषी बाजार',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Pan-India electronic trading portal connecting APMC mandis for better price discovery.',descriptionMarathi:'APMC मंडींना जोडणारे इलेक्ट्रॉनिक ट्रेडिंग पोर्टल — योग्य भाव मिळवण्यासाठी.',benefits:['Better price discovery via online auction','Transparent bidding process','Online payment within 24 hours','Access to pan-India buyers'],eligibility:['All registered farmers','Must have Aadhaar & bank account'],documents:['Aadhaar Card','Bank Account','Land Records','Mobile Number'],howToApply:'Register at enam.gov.in or visit local APMC mandi',link:'https://enam.gov.in',category:'market',color:'#f59e0b'},
  {id:5,name:'PMKSY',fullName:'Pradhan Mantri Krishi Sinchayee Yojana',fullNameMarathi:'प्रधानमंत्री कृषी सिंचाई योजना',ministry:'Ministry of Jal Shakti',description:'Har Khet Ko Pani — ensuring water to every farm through micro-irrigation systems.',descriptionMarathi:'हर खेत को पानी — ठिबक/तुषार सिंचनाद्वारे जलवापर कार्यक्षमता.',benefits:['Drip irrigation subsidy 55–75%','Sprinkler irrigation subsidy','10% additional for SC/ST','Convergence of water schemes'],eligibility:['All farmers','Priority to small & marginal'],documents:['Aadhaar Card','Land Records','Bank Account','Equipment quotation'],howToApply:'Apply at District Agriculture Office or pmksy.gov.in',link:'https://pmksy.gov.in',category:'irrigation',color:'#0891b2'},
  {id:6,name:'PKVY',fullName:'Paramparagat Krishi Vikas Yojana',fullNameMarathi:'परंपरागत कृषी विकास योजना',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Promotes organic farming with ₹50,000/hectare assistance over 3 years.',descriptionMarathi:'जैविक शेतीला प्रोत्साहन — 3 वर्षांत ₹50,000/हेक्टर सहाय्य.',benefits:['₹50,000/hectare over 3 years','Organic certification support','Better market linkage','Soil health improvement'],eligibility:['Groups of 50+ farmers','Minimum 50 acres cluster'],documents:['Aadhaar Card','Land Records','Group formation documents'],howToApply:'Apply through State Agriculture Department',link:'https://pgsindia-ncof.gov.in',category:'organic',color:'#059669'},
  {id:7,name:'Soil Health Card',fullName:'Soil Health Card Scheme',fullNameMarathi:'माती आरोग्य कार्ड योजना',ministry:'Ministry of Agriculture & Farmers Welfare',description:'Free soil testing with crop-wise fertilizer recommendations for farmers.',descriptionMarathi:'शेतकऱ्यांना मोफत माती तपासणी आणि पीकनिहाय खत शिफारसी.',benefits:['Free soil testing every 2 years','Crop-specific fertilizer recommendations','Reduces input costs 8–10%','Improves soil health & yield'],eligibility:['All farmers — no restrictions'],documents:['Aadhaar Card','Mobile number'],howToApply:'Contact nearest Krishi Vigyan Kendra or soilhealth.dac.gov.in',link:'https://soilhealth.dac.gov.in',category:'soil',color:'#78350f'},
  {id:8,name:'Namo Shetkari',fullName:'Namo Shetkari Maha Samman Nidhi',fullNameMarathi:'नमो शेतकरी महासन्मान निधी योजना',ministry:'Maharashtra State Government',description:'Maharashtra scheme adding ₹6,000/year on top of PM-KISAN — total ₹12,000 annual benefit.',descriptionMarathi:'PM-KISAN वर अतिरिक्त ₹6,000 — महाराष्ट्र शेतकऱ्यांना एकूण ₹12,000 वार्षिक लाभ.',benefits:['Additional ₹6,000/year (state)','Total ₹12,000 with PM-KISAN','Direct bank transfer','Auto-enrolled if you receive PM-KISAN'],eligibility:['All PM-KISAN beneficiaries in Maharashtra'],documents:['Aadhaar Card','Bank Account','7/12 Utara'],howToApply:'Auto-enrolled if receiving PM-KISAN. Contact Agriculture Office.',link:'https://krishi.maharashtra.gov.in',category:'state',color:'#7c3aed'},
];
router.get('/', (req, res) => res.json(req.query.category ? schemes.filter(s=>s.category===req.query.category) : schemes));
router.get('/:id', (req, res) => { const s = schemes.find(s=>s.id===+req.params.id); s?res.json(s):res.status(404).json({message:'Not found'}); });
module.exports = router;
